//
// Autogenerated by Thrift Compiler (0.14.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = require('./account_types');
//HELPER FUNCTIONS AND STRUCTURES

var TAccountService_createAccount_args = function(args) {
  this.tAccountRpcDTO = null;
  if (args) {
    if (args.tAccountRpcDTO !== undefined && args.tAccountRpcDTO !== null) {
      this.tAccountRpcDTO = new ttypes.TAccountRpcDTO(args.tAccountRpcDTO);
    }
  }
};
TAccountService_createAccount_args.prototype = {};
TAccountService_createAccount_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.tAccountRpcDTO = new ttypes.TAccountRpcDTO();
        this.tAccountRpcDTO.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TAccountService_createAccount_args.prototype.write = function(output) {
  output.writeStructBegin('TAccountService_createAccount_args');
  if (this.tAccountRpcDTO !== null && this.tAccountRpcDTO !== undefined) {
    output.writeFieldBegin('tAccountRpcDTO', Thrift.Type.STRUCT, 1);
    this.tAccountRpcDTO.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TAccountService_createAccount_result = function(args) {
};
TAccountService_createAccount_result.prototype = {};
TAccountService_createAccount_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TAccountService_createAccount_result.prototype.write = function(output) {
  output.writeStructBegin('TAccountService_createAccount_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TAccountService_getAccount_args = function(args) {
  this.uid = null;
  if (args) {
    if (args.uid !== undefined && args.uid !== null) {
      this.uid = args.uid;
    }
  }
};
TAccountService_getAccount_args.prototype = {};
TAccountService_getAccount_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.uid = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TAccountService_getAccount_args.prototype.write = function(output) {
  output.writeStructBegin('TAccountService_getAccount_args');
  if (this.uid !== null && this.uid !== undefined) {
    output.writeFieldBegin('uid', Thrift.Type.I64, 1);
    output.writeI64(this.uid);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TAccountService_getAccount_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.TAccountRpcDTO(args.success);
    }
  }
};
TAccountService_getAccount_result.prototype = {};
TAccountService_getAccount_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.TAccountRpcDTO();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TAccountService_getAccount_result.prototype.write = function(output) {
  output.writeStructBegin('TAccountService_getAccount_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TAccountServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
TAccountServiceClient.prototype = {};
TAccountServiceClient.prototype.seqid = function() { return this._seqid; };
TAccountServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

TAccountServiceClient.prototype.createAccount = function(tAccountRpcDTO, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_createAccount(tAccountRpcDTO);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_createAccount(tAccountRpcDTO);
  }
};

TAccountServiceClient.prototype.send_createAccount = function(tAccountRpcDTO) {
  var output = new this.pClass(this.output);
  var params = {
    tAccountRpcDTO: tAccountRpcDTO
  };
  var args = new TAccountService_createAccount_args(params);
  try {
    output.writeMessageBegin('createAccount', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

TAccountServiceClient.prototype.recv_createAccount = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new TAccountService_createAccount_result();
  result.read(input);
  input.readMessageEnd();

  callback(null);
};

TAccountServiceClient.prototype.getAccount = function(uid, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getAccount(uid);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getAccount(uid);
  }
};

TAccountServiceClient.prototype.send_getAccount = function(uid) {
  var output = new this.pClass(this.output);
  var params = {
    uid: uid
  };
  var args = new TAccountService_getAccount_args(params);
  try {
    output.writeMessageBegin('getAccount', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

TAccountServiceClient.prototype.recv_getAccount = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new TAccountService_getAccount_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getAccount failed: unknown result');
};
var TAccountServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
TAccountServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
TAccountServiceProcessor.prototype.process_createAccount = function(seqid, input, output) {
  var args = new TAccountService_createAccount_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.createAccount.length === 1) {
    Q.fcall(this._handler.createAccount.bind(this._handler),
      args.tAccountRpcDTO
    ).then(function(result) {
      var result_obj = new TAccountService_createAccount_result({success: result});
      output.writeMessageBegin("createAccount", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("createAccount", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.createAccount(args.tAccountRpcDTO, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new TAccountService_createAccount_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("createAccount", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("createAccount", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
TAccountServiceProcessor.prototype.process_getAccount = function(seqid, input, output) {
  var args = new TAccountService_getAccount_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getAccount.length === 1) {
    Q.fcall(this._handler.getAccount.bind(this._handler),
      args.uid
    ).then(function(result) {
      var result_obj = new TAccountService_getAccount_result({success: result});
      output.writeMessageBegin("getAccount", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("getAccount", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.getAccount(args.uid, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new TAccountService_getAccount_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("getAccount", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getAccount", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
